-- prep_tips for the 18 new milestone windows added in 20260319_new_milestone_windows.sql
-- Run after: 20260319_prep_tips.sql

UPDATE milestone_windows SET prep_tip = 'Pick up a small weighted open cup before this window opens — a shot glass size works perfectly. Introduce it at one meal a day with just an inch of water. Spills are expected and fine; that''s how the skill develops.' WHERE slug = 'self-help-open-cup';
UPDATE milestone_windows SET prep_tip = 'You don''t need to do anything special to prepare — just resist the urge to stop the switch-flipping, drawer-opening, and button-pressing that''s about to begin. It looks like mischief. It''s actually deliberate learning.' WHERE slug = 'cognitive-cause-effect-exploration';
UPDATE milestone_windows SET prep_tip = 'Check your stair gates are securely latched — descending attempts are coming and they''re less coordinated than ascending. Show your child the feet-first, backward method a few times before the window opens. Demonstrate it slowly, repeat it every time.' WHERE slug = 'motor-stairs-descending';
UPDATE milestone_windows SET prep_tip = 'Start building a few extra minutes into your morning routine now. The shift from dressing your child to dressing with your child takes patience more than anything else. Loose-fitting tops and elastic waistbands make the early attempts much easier.' WHERE slug = 'self-help-self-dressing-assist';
UPDATE milestone_windows SET prep_tip = 'Don''t start training yet — just start watching. The signs to note: staying dry for 2 hours or more, pulling at a wet diaper, showing interest in the toilet, or hiding to poop. Jot down what you see over the next few weeks. That observation period makes the actual training faster.' WHERE slug = 'self-help-potty-readiness';
UPDATE milestone_windows SET prep_tip = 'Stock up on patience now — the question explosion is coming and it arrives fast. ''What''s that?'' will become the most-used phrase in your house. The parents who answer every question genuinely, even the repetitive ones, see faster vocabulary growth. It''s worth the mental energy.' WHERE slug = 'language-question-asking';
UPDATE milestone_windows SET prep_tip = 'Pick up a large soft foam ball if you don''t have one — about the size of a tennis ball is ideal. Clear some open space, indoors or out. That''s the whole preparation. Your enthusiasm for the attempts is the main driver of practice.' WHERE slug = 'motor-throw-overarm';
UPDATE milestone_windows SET prep_tip = 'Get a box of thick crayons and a roll of cheap paper — tape it to a low surface or the fridge. The goal is access, not instruction. When you sit down to draw, draw a slow vertical line and invite them to try. Keep expectations low and paper plentiful.' WHERE slug = 'cognitive-draw-copy-lines';
UPDATE milestone_windows SET prep_tip = 'Be ready to laugh at deliberately wrong answers. When your child points at a dog and says ''cat!'' with a grin, that''s a joke — intentional expectation violation. Your reaction is the entire reward. Children who get a genuine laugh double down on humor.' WHERE slug = 'cognitive-humor-jokes';
UPDATE milestone_windows SET prep_tip = 'If you''re choosing between a tricycle and a balance bike, choose the balance bike — it builds the balance and steering skills that transfer directly to a pedal bike later. Buy it a few weeks before this window opens so it''s already familiar when the skill is ready to develop.' WHERE slug = 'motor-tricycle-balance-bike';
UPDATE milestone_windows SET prep_tip = 'Start letting your child undress at bath time and bedtime without help. Velcro shoes and elastic waistbands are the right gear for this learning phase — laces and buttons come later. Giving them the job now, before they insist on it, makes the transition much smoother.' WHERE slug = 'self-help-undressing-independently';
UPDATE milestone_windows SET prep_tip = 'Get a second toothbrush so your child has their own to hold while you do the actual brushing. Letting them choose the toothpaste flavor — from two options — reduces resistance before it starts. The goal right now is the habit, not the technique.' WHERE slug = 'self-help-tooth-brushing';
UPDATE milestone_windows SET prep_tip = 'Start paying attention to which hand your child reaches with consistently. Don''t try to influence it — handedness is neurological, not a habit. If it''s looking like the left hand, source left-handed scissors now before preschool starts, and flag it to caregivers so nobody redirects.' WHERE slug = 'motor-handedness-emerging';
UPDATE milestone_windows SET prep_tip = 'If your child is in daycare or a playgroup, ask the caregivers which children they gravitate toward. When a name starts coming up at home, take it seriously — arrange a one-on-one playdate. Short, same-age, low-structure play is the format that builds real friendships at this age.' WHERE slug = 'social-named-friendships';
UPDATE milestone_windows SET prep_tip = 'Turn balance into a game before the window formally opens: flamingo pose during tooth brushing, stepping stones at the park, counting how long they can hold it. Two seconds is the milestone target at 36 months — children who''ve been playing with balance get there faster.' WHERE slug = 'motor-balance-one-foot';
UPDATE milestone_windows SET prep_tip = 'If preschool starts in the next 6 months, visit the classroom together before the first day — familiarity dramatically reduces first-day distress. Also check in on the three practical skills that matter most for preschool readiness: can they follow a 2-step instruction, separate briefly from you, and manage basic self-help tasks.' WHERE slug = 'cognitive-preschool-readiness';
UPDATE milestone_windows SET prep_tip = 'Lay out tomorrow''s clothes the night before and start letting your child get dressed independently in the morning — before the time pressure of leaving the house kicks in. Elastic waists, Velcro, and slip-on shoes are the right gear. Remove the friction from the setup and the skill develops quickly.' WHERE slug = 'self-help-dressing-simple-clothes';
UPDATE milestone_windows SET prep_tip = 'Start emphasizing the total when you count together: ''One, two, three crackers — you have three!'' The final number as a quantity is the concept they''re building, not just the counting sequence. Embed it in daily life — stairs, crackers, toys being put away.' WHERE slug = 'cognitive-number-quantity';