-- ─── jack_bridge text for all 198 milestone windows ─────────────────────────
-- Jack's voice: direct, warm, research-backed, occasionally wry.
-- One sentence. No exclamation marks. No fluff. Gender-neutral.

UPDATE milestone_windows SET jack_bridge = 'Newborns don''t see pastels — they see faces and high contrast.' WHERE slug = 'cognitive-visual-stimulation';
UPDATE milestone_windows SET jack_bridge = 'The research on this is cleaner than almost anything else in child development: daily reading wins.' WHERE slug = 'language-read-aloud-daily';
UPDATE milestone_windows SET jack_bridge = 'Harvard calls this the most important thing you can do for your baby''s brain.' WHERE slug = 'language-serve-return';
UPDATE milestone_windows SET jack_bridge = 'Nursery rhymes are the earliest reading prep — phonological awareness starts here.' WHERE slug = 'language-songs-rhymes';
UPDATE milestone_windows SET jack_bridge = 'These early sound responses are the first hearing screen you can do at home.' WHERE slug = 'language-startle-to-sound';
UPDATE milestone_windows SET jack_bridge = 'Most parents don''t do enough — 15 to 30 minutes a day is the target.' WHERE slug = 'motor-tummy-time-build';
UPDATE milestone_windows SET jack_bridge = 'I started late with First Son. He developed flat head. Start from day three.' WHERE slug = 'motor-tummy-time-start';
UPDATE milestone_windows SET jack_bridge = 'After week 16, many babies refuse a bottle entirely — the window is narrower than most parents expect.' WHERE slug = 'nutrition-bottle-intro-breastfed';
UPDATE milestone_windows SET jack_bridge = 'The first 8 weeks set your supply for the months that follow.' WHERE slug = 'nutrition-breastfeeding-establishment';
UPDATE milestone_windows SET jack_bridge = 'No exceptions — not raw honey, not cooked, not in any form.' WHERE slug = 'nutrition-honey-avoidance';
UPDATE milestone_windows SET jack_bridge = 'Breast milk is nearly perfect. Vitamin D is the one gap.' WHERE slug = 'nutrition-vitamin-d-breastfed';
UPDATE milestone_windows SET jack_bridge = 'Check the label — and check how much your baby is actually drinking per day.' WHERE slug = 'nutrition-vitamin-d-formula';
UPDATE milestone_windows SET jack_bridge = 'One rule. Every sleep. Every person who cares for this baby.' WHERE slug = 'safety-back-to-sleep';
UPDATE milestone_windows SET jack_bridge = '75% of car seats are installed incorrectly — the hospital parking lot is not the time to figure this out.' WHERE slug = 'safety-car-seat-install-check';
UPDATE milestone_windows SET jack_bridge = 'Two hours of training. Potentially the most important two hours of this entire year.' WHERE slug = 'safety-infant-cpr';
UPDATE milestone_windows SET jack_bridge = 'Save the number now — you won''t want to search for it when your toddler has eaten something.' WHERE slug = 'safety-poison-control';
UPDATE milestone_windows SET jack_bridge = 'Same room, separate surface — 50% less SIDS risk at zero cost.' WHERE slug = 'safety-room-sharing';
UPDATE milestone_windows SET jack_bridge = '60% of newborns get jaundice — most are fine, some aren''t, this is how you tell the difference.' WHERE slug = 'screening-newborn-bilirubin';
UPDATE milestone_windows SET jack_bridge = 'One heel prick, thirty conditions caught — one of the highest-value tests in all of pediatric medicine.' WHERE slug = 'screening-newborn-blood-spot';
UPDATE milestone_windows SET jack_bridge = 'Ten minutes, painless, and the earlier hearing loss is caught the better the language outcomes.' WHERE slug = 'screening-newborn-hearing';
UPDATE milestone_windows SET jack_bridge = 'Most parents don''t know this visit exists — it''s the one that catches what the discharge check missed.' WHERE slug = 'screening-visit-3to5-days';
UPDATE milestone_windows SET jack_bridge = 'Active involvement from day one changes what kind of parent you become.' WHERE slug = 'social-father-partner-bonding';
UPDATE milestone_windows SET jack_bridge = '1 in 5 mothers, 1 in 10 fathers — and untreated postpartum depression affects the child, not just the parent.' WHERE slug = 'social-parent-depression-screening';
UPDATE milestone_windows SET jack_bridge = 'This isn''t self-indulgence — a depleted parent cannot regulate a dysregulated child.' WHERE slug = 'social-parent-self-care';
UPDATE milestone_windows SET jack_bridge = 'Secure attachment is built not through any single action — it''s the sum of thousands of small responses.' WHERE slug = 'social-primary-attachment';
UPDATE milestone_windows SET jack_bridge = 'Every response to a reach, a sound, a look — this is how a young nervous system learns it''s safe.' WHERE slug = 'social-serve-return-loop';
UPDATE milestone_windows SET jack_bridge = 'The first hour after birth is the most neurologically receptive window of your baby''s entire life.' WHERE slug = 'social-skin-to-skin';
UPDATE milestone_windows SET jack_bridge = 'Most parents don''t know this visit exists — it''s on the AAP schedule for good reason.' WHERE slug = 'screening-visit-1month';
UPDATE milestone_windows SET jack_bridge = 'Recognition starts with smell, then face and voice — the brain is already building its most important relationship.' WHERE slug = 'cognitive-recognizes-caregiver';
UPDATE milestone_windows SET jack_bridge = 'Smooth visual tracking is the first sign the eyes and brain are working together.' WHERE slug = 'cognitive-visual-tracking';
UPDATE milestone_windows SET jack_bridge = 'This is the first time they''re choosing to make a sound — it''s not random.' WHERE slug = 'language-cooing';
UPDATE milestone_windows SET jack_bridge = 'Head control by 4 months is the prerequisite for almost every gross motor milestone that follows.' WHERE slug = 'motor-head-control';
UPDATE milestone_windows SET jack_bridge = 'This happens automatically at the hospital — but you should know what it is before results come back.' WHERE slug = 'prebirth-newborn-screening';
UPDATE milestone_windows SET jack_bridge = 'A swaddled baby who rolls cannot push their face away from the mattress — this is the stopping point.' WHERE slug = 'safety-swaddle-transition';
UPDATE milestone_windows SET jack_bridge = 'How you handle the first handoff shapes how they handle every one after it.' WHERE slug = 'social-caregiver-transition';
UPDATE milestone_windows SET jack_bridge = 'The reflex smile is gas — this one is a deliberate choice, and it changes everything.' WHERE slug = 'social-social-smile-appears';
UPDATE milestone_windows SET jack_bridge = 'The postpartum period is foggier than you expect — pack it now, when you can still think clearly.' WHERE slug = 'prebirth-hospital-bag';
UPDATE milestone_windows SET jack_bridge = 'The time to set this up is before you''re exhausted with a newborn in your arms.' WHERE slug = 'prebirth-safe-sleep-setup';
UPDATE milestone_windows SET jack_bridge = 'The first laugh out loud is the brain making deeper social connections — not just a reflex.' WHERE slug = 'language-laughing';
UPDATE milestone_windows SET jack_bridge = 'This is the first intentional movement — the beginning of doing things on purpose.' WHERE slug = 'motor-reaching-grabbing';
UPDATE milestone_windows SET jack_bridge = 'Usually happens by accident before it''s deliberate — and then suddenly they''re mobile.' WHERE slug = 'motor-roll-tummy-to-back';
UPDATE milestone_windows SET jack_bridge = 'The 2-month visit starts the vaccine schedule and the first real developmental assessment.' WHERE slug = 'screening-visit-2months';
UPDATE milestone_windows SET jack_bridge = 'The first visit happens within 3 days of birth — that is not the time to start researching.' WHERE slug = 'prebirth-pediatrician-selection';
UPDATE milestone_windows SET jack_bridge = 'Until this clicks, they think the mirror baby is someone else.' WHERE slug = 'cognitive-self-recognition-mirror';
UPDATE milestone_windows SET jack_bridge = 'Harder than the first direction — and once they can do this, they get into tummy time on their own.' WHERE slug = 'motor-roll-back-to-tummy';
UPDATE milestone_windows SET jack_bridge = 'Supported sitting is the bridge to independent sitting — and the prerequisite for solid foods.' WHERE slug = 'motor-sitting-supported';
UPDATE milestone_windows SET jack_bridge = 'Same steps, same order, every night — predictability is how a young brain learns it''s safe.' WHERE slug = 'social-bedtime-routine-security';
UPDATE milestone_windows SET jack_bridge = 'This isn''t a setback — it''s the brain permanently rewiring its sleep architecture.' WHERE slug = 'cognitive-sleep-regression-4month';
UPDATE milestone_windows SET jack_bridge = 'The beginning of understanding that things still exist even when they disappear.' WHERE slug = 'cognitive-object-permanence-emerging';
UPDATE milestone_windows SET jack_bridge = 'Imitation is how humans learn almost everything — and it starts here.' WHERE slug = 'language-imitating-sounds';
UPDATE milestone_windows SET jack_bridge = 'This is more than a party trick — it''s a key social-cognitive milestone.' WHERE slug = 'language-responds-to-name';
UPDATE milestone_windows SET jack_bridge = 'No cow''s milk to drink yet — but yogurt and cheese start now.' WHERE slug = 'nutrition-dairy-intro';
UPDATE milestone_windows SET jack_bridge = 'Same logic as peanuts — early introduction significantly reduces lifelong allergy risk.' WHERE slug = 'nutrition-egg-intro';
UPDATE milestone_windows SET jack_bridge = 'At this stage, food is for practice — milk is still doing the nutritional heavy lifting.' WHERE slug = 'nutrition-first-purees';
UPDATE milestone_windows SET jack_bridge = 'Fish is a two-for-one: allergen exposure and DHA for brain development in one introduction.' WHERE slug = 'nutrition-fish-intro';
UPDATE milestone_windows SET jack_bridge = 'Iron stores run out around 6 months — and the developing brain does not tolerate deficiency well.' WHERE slug = 'nutrition-iron-fortified-foods';
UPDATE milestone_windows SET jack_bridge = 'Breast milk is nearly perfect — but it doesn''t cover iron needs after 4 months.' WHERE slug = 'nutrition-iron-supplement-breastfed';
UPDATE milestone_windows SET jack_bridge = 'The old advice was to avoid peanuts. The new advice is the opposite — and the evidence is overwhelming.' WHERE slug = 'nutrition-peanut-intro';
UPDATE milestone_windows SET jack_bridge = 'New to the major allergen list — and the early introduction window applies here too.' WHERE slug = 'nutrition-sesame-intro';
UPDATE milestone_windows SET jack_bridge = 'Starting before readiness causes problems. Starting after readiness misses a window.' WHERE slug = 'nutrition-solids-readiness';
UPDATE milestone_windows SET jack_bridge = 'Soy is top 9 — and the early introduction principle applies as much here as anywhere.' WHERE slug = 'nutrition-soy-intro';
UPDATE milestone_windows SET jack_bridge = 'Tree nuts and peanuts are different allergens — tolerating one does not mean tolerating the other.' WHERE slug = 'nutrition-tree-nut-intro';
UPDATE milestone_windows SET jack_bridge = 'Early introduction may reduce the risk of wheat allergy — and potentially Celiac disease.' WHERE slug = 'nutrition-wheat-intro';
UPDATE milestone_windows SET jack_bridge = 'Once they''re mobile, you''ll wish you''d done this last week.' WHERE slug = 'safety-babyproofing';
UPDATE milestone_windows SET jack_bridge = 'Baby teeth matter — tooth decay in infancy predicts poor dental health for life.' WHERE slug = 'screening-dental-first-visit';
UPDATE milestone_windows SET jack_bridge = 'The 4-month visit is also when the sleep regression gets discussed — come prepared for both.' WHERE slug = 'screening-visit-4months';
UPDATE milestone_windows SET jack_bridge = 'It''s teaching three things at once: you exist, you come back, and games have a structure.' WHERE slug = 'social-peek-a-boo';
UPDATE milestone_windows SET jack_bridge = 'Every drop off the high chair tray is a physics experiment — it is not misbehavior.' WHERE slug = 'cognitive-cause-effect';
UPDATE milestone_windows SET jack_bridge = 'Moving an object from one hand to the other is the first sign both brain hemispheres are coordinating.' WHERE slug = 'motor-object-transfer';
UPDATE milestone_windows SET jack_bridge = 'Independent sitting frees both hands for exploration — and unlocks the high chair.' WHERE slug = 'motor-sitting-unsupported';
UPDATE milestone_windows SET jack_bridge = 'Babies understand ''more'' and ''all done'' before they have words for them — signs can come first.' WHERE slug = 'cognitive-more-all-done';
UPDATE milestone_windows SET jack_bridge = 'Babble frequency and variety at this stage actually predict vocabulary size at 18 months.' WHERE slug = 'language-babbling';
UPDATE milestone_windows SET jack_bridge = 'Pointing to pictures while naming them produces measurably larger vocabulary by age 2.' WHERE slug = 'language-read-with-pointing';
UPDATE milestone_windows SET jack_bridge = 'Songs encode language in melody — which makes words significantly easier to remember.' WHERE slug = 'language-singing-together';
UPDATE milestone_windows SET jack_bridge = 'This is the first time they get to choose where they go.' WHERE slug = 'motor-crawling';
UPDATE milestone_windows SET jack_bridge = 'Dental patterns established before age 2 predict adult cavity risk.' WHERE slug = 'nutrition-dental-diet';
UPDATE milestone_windows SET jack_bridge = 'Start the cup at 6 months — the goal is full bottle transition at the first birthday.' WHERE slug = 'nutrition-sippy-cup';
UPDATE milestone_windows SET jack_bridge = 'Stay on smooth purees too long and texture aversion becomes the next problem.' WHERE slug = 'nutrition-texture-mashed';
UPDATE milestone_windows SET jack_bridge = 'Water at meals is about building the cup habit, not hydration — milk handles that.' WHERE slug = 'nutrition-water-cup';
UPDATE milestone_windows SET jack_bridge = 'Sunburn in infancy raises lifetime melanoma risk — shade and cover first, then sunscreen.' WHERE slug = 'safety-sunscreen-6months';
UPDATE milestone_windows SET jack_bridge = 'The leading cause of death for children ages 1 to 4. Two inches of water is enough.' WHERE slug = 'safety-water-supervision';
UPDATE milestone_windows SET jack_bridge = 'There is no safe level of lead exposure in children — the question is whether your environment has any.' WHERE slug = 'screening-blood-lead';
UPDATE milestone_windows SET jack_bridge = 'The 6-month visit is the green light for solid food introduction — bring your questions.' WHERE slug = 'screening-visit-6months';
UPDATE milestone_windows SET jack_bridge = 'Separation anxiety is not a sign something is wrong — it''s proof the attachment is working.' WHERE slug = 'social-separation-anxiety';
UPDATE milestone_windows SET jack_bridge = 'Wariness of strangers is a feature of healthy attachment, not a problem to solve.' WHERE slug = 'social-stranger-anxiety';
UPDATE milestone_windows SET jack_bridge = 'Understanding ''no'' before saying it — receptive language always runs ahead of expressive.' WHERE slug = 'language-understands-no';
UPDATE milestone_windows SET jack_bridge = 'Once they''re pulling up, everything on low tables and counters is now within reach.' WHERE slug = 'motor-pull-to-stand';
UPDATE milestone_windows SET jack_bridge = 'Self-feeding isn''t just a nutrition strategy — it''s how the pincer grasp develops.' WHERE slug = 'nutrition-texture-finger-foods';
UPDATE milestone_windows SET jack_bridge = 'Pointing to share something, then looking back to check your reaction — this matters more than first words.' WHERE slug = 'social-joint-attention';
UPDATE milestone_windows SET jack_bridge = 'Mimicking your actions is building the neural foundation for all social learning.' WHERE slug = 'cognitive-imitation-play';
UPDATE milestone_windows SET jack_bridge = 'Searching for a completely hidden toy means holding a mental image of it — thinking without seeing.' WHERE slug = 'cognitive-object-permanence-solid';
UPDATE milestone_windows SET jack_bridge = 'It looks like a social nicety — it''s actually the first deliberate body-language communication.' WHERE slug = 'language-waving';
UPDATE milestone_windows SET jack_bridge = 'The last step before first steps — the legs are almost ready.' WHERE slug = 'motor-cruising';
UPDATE milestone_windows SET jack_bridge = 'Thumb and index finger pinching is the prerequisite for self-feeding, drawing, and eventually writing.' WHERE slug = 'motor-pincer-grasp';
UPDATE milestone_windows SET jack_bridge = 'Three meals a day isn''t just feeding — it''s setting a metabolic rhythm for the next decade.' WHERE slug = 'nutrition-3-meals-rhythm';
UPDATE milestone_windows SET jack_bridge = 'Babies who feed themselves learn to stop when full — one of the most useful habits they''ll ever develop.' WHERE slug = 'nutrition-self-feeding-pincer';
UPDATE milestone_windows SET jack_bridge = 'In and out, over and over — they''re running a spatial reasoning experiment, not making a mess.' WHERE slug = 'cognitive-container-play';
UPDATE milestone_windows SET jack_bridge = 'The sound existed for months — the specific meaning just arrived.' WHERE slug = 'language-mama-dada-specific';
UPDATE milestone_windows SET jack_bridge = 'The 9-month visit is the first formal developmental screen using a standardised tool.' WHERE slug = 'screening-visit-9months';
UPDATE milestone_windows SET jack_bridge = 'Failure and retry built into the toy — this is structured problem solving.' WHERE slug = 'cognitive-shape-sorter';
UPDATE milestone_windows SET jack_bridge = 'They understand far more words than they can say — receptive language always leads expressive.' WHERE slug = 'language-receptive-vocabulary';
UPDATE milestone_windows SET jack_bridge = 'The clinical red flag is 18 months, not 12 — first steps anywhere up to 15 months is normal.' WHERE slug = 'motor-first-steps';
UPDATE milestone_windows SET jack_bridge = 'Connecting a picture on a page to the real thing it represents is a genuine cognitive leap.' WHERE slug = 'cognitive-points-to-pictures';
UPDATE milestone_windows SET jack_bridge = 'What counts is consistent, intentional use — not perfect pronunciation.' WHERE slug = 'language-first-words';
UPDATE milestone_windows SET jack_bridge = 'The clinical red flag is 18 months — a child cruising at 15 months is developing normally.' WHERE slug = 'motor-walking-independent';
UPDATE milestone_windows SET jack_bridge = 'Prolonged bottle use is one of the leading causes of infant tooth decay.' WHERE slug = 'nutrition-bottle-weaning';
UPDATE milestone_windows SET jack_bridge = 'The short-order cook starts here — or it doesn''t. This is when the pattern sets.' WHERE slug = 'nutrition-family-foods';
UPDATE milestone_windows SET jack_bridge = 'Pointing to their nose when asked requires understanding that things have labels — including themselves.' WHERE slug = 'cognitive-identifies-body-parts';
UPDATE milestone_windows SET jack_bridge = 'Feeding a stuffed animal is the beginning of symbolic thinking — and symbolic thinking is the foundation of reading.' WHERE slug = 'cognitive-pretend-play-emerging';
UPDATE milestone_windows SET jack_bridge = 'Following an instruction without a gesture means language is doing the work, not context.' WHERE slug = 'language-1step-commands';
UPDATE milestone_windows SET jack_bridge = 'Naming the feeling isn''t just describing — it actually reduces the intensity of the emotion in the brain.' WHERE slug = 'language-label-emotions';
UPDATE milestone_windows SET jack_bridge = 'Each block placed requires depth perception, a steady hand, and deliberate grip release.' WHERE slug = 'motor-stacking-blocks-3';
UPDATE milestone_windows SET jack_bridge = 'The switch happens at 12 months — whole milk before then, whole milk until 2 years.' WHERE slug = 'nutrition-cows-milk-switch';
UPDATE milestone_windows SET jack_bridge = 'Eating patterns set before age 2 are the ones that show up at school age.' WHERE slug = 'nutrition-healthy-snack-patterns';
UPDATE milestone_windows SET jack_bridge = 'Too much milk after 12 months crowds out the solid food that has the iron.' WHERE slug = 'nutrition-milk-cap';
UPDATE milestone_windows SET jack_bridge = 'The mess is how the motor skill develops — resist the urge to take the spoon.' WHERE slug = 'nutrition-spoon-self-feeding';
UPDATE milestone_windows SET jack_bridge = 'The visual system is still developing — catching problems before age 3 produces significantly better outcomes.' WHERE slug = 'screening-vision-12months';
UPDATE milestone_windows SET jack_bridge = 'The 12-month visit checks walking, first words, and pointing — all at the same time.' WHERE slug = 'screening-visit-12months';
UPDATE milestone_windows SET jack_bridge = 'The approach matters less than whether you apply it the same way every time.' WHERE slug = 'social-consistent-discipline';
UPDATE milestone_windows SET jack_bridge = 'Saying ''you''re so frustrated'' during the meltdown is not just describing — it''s actively intervening.' WHERE slug = 'social-label-big-feelings';
UPDATE milestone_windows SET jack_bridge = 'Playing near each other but not with each other is exactly where 2-year-olds are supposed to be.' WHERE slug = 'social-parallel-play';
UPDATE milestone_windows SET jack_bridge = 'Ten words is the milestone that unlocks the next one — vocabulary tends to accelerate from here.' WHERE slug = 'language-vocab-10-words';
UPDATE milestone_windows SET jack_bridge = 'Up before down — ascending a stair requires less balance than descending.' WHERE slug = 'motor-stair-climbing';
UPDATE milestone_windows SET jack_bridge = 'The sippy cup is a transition tool, not a long-term solution — 18 months is the AAP''s limit.' WHERE slug = 'self-help-open-cup';
UPDATE milestone_windows SET jack_bridge = 'Every drawer opened and closed repeatedly is a hypothesis being tested — not misbehavior.' WHERE slug = 'cognitive-cause-effect-exploration';
UPDATE milestone_windows SET jack_bridge = 'Animal names and sounds are often the first vocabulary burst — acoustically distinct and emotionally engaging.' WHERE slug = 'cognitive-animals-sounds';
UPDATE milestone_windows SET jack_bridge = 'Kicking requires standing briefly on one leg — a balance skill that''s harder than it looks.' WHERE slug = 'motor-kicking-ball';
UPDATE milestone_windows SET jack_bridge = 'Running emerges about six months after walking — when momentum stops being a threat.' WHERE slug = 'motor-running';
UPDATE milestone_windows SET jack_bridge = 'The scribble is the beginning of a long path that ends in writing.' WHERE slug = 'motor-scribbling';
UPDATE milestone_windows SET jack_bridge = 'Six blocks is precision work — the fine motor control required here is significant.' WHERE slug = 'motor-stacking-blocks-6';
UPDATE milestone_windows SET jack_bridge = 'Stabbing is easier than scooping — forks often become the preferred utensil quickly.' WHERE slug = 'nutrition-fork-intro';
UPDATE milestone_windows SET jack_bridge = 'The 15-month visit is the first real language checkpoint — come with a word count ready.' WHERE slug = 'screening-visit-15months';
UPDATE milestone_windows SET jack_bridge = 'Going down requires more balance than going up — and a fall is more likely on the descent.' WHERE slug = 'motor-stairs-descending';
UPDATE milestone_windows SET jack_bridge = 'Letting them push the arm through the sleeve now is what makes dressing independently at 4 possible.' WHERE slug = 'self-help-self-dressing-assist';
UPDATE milestone_windows SET jack_bridge = 'When they offer their comfort object to someone who looks sad, that''s the first real empathy.' WHERE slug = 'social-comforting-behavior';
UPDATE milestone_windows SET jack_bridge = 'Knowing a spoon is for eating is different from knowing its name — this is functional understanding.' WHERE slug = 'cognitive-function-of-objects';
UPDATE milestone_windows SET jack_bridge = 'Sorting by a shared property is the beginning of mathematical thinking.' WHERE slug = 'cognitive-matches-shapes-colors';
UPDATE milestone_windows SET jack_bridge = 'Understanding ''mine'' and ''yours'' is a theory of mind skill — and the prerequisite for real sharing.' WHERE slug = 'cognitive-mine-yours';
UPDATE milestone_windows SET jack_bridge = 'Multi-step pretend play is narrative thinking — one of the strongest predictors of reading ability.' WHERE slug = 'cognitive-pretend-play-complex';
UPDATE milestone_windows SET jack_bridge = 'Using a stick to reach something is the first sign of means-end thinking.' WHERE slug = 'cognitive-simple-problem-solving';
UPDATE milestone_windows SET jack_bridge = '''More milk'' is not just two words — it''s the first time they''re constructing meaning.' WHERE slug = 'language-2-word-combinations';
UPDATE milestone_windows SET jack_bridge = 'Five body parts sounds modest — it''s evidence of significant receptive vocabulary growth.' WHERE slug = 'language-body-parts-5';
UPDATE milestone_windows SET jack_bridge = 'If even the people who know them best are struggling to understand, that''s the evaluation flag.' WHERE slug = 'language-speech-clarity-family';
UPDATE milestone_windows SET jack_bridge = 'Fifty words is the gate — vocabulary tends to explode after this point.' WHERE slug = 'language-vocab-50-words';
UPDATE milestone_windows SET jack_bridge = 'Most experts recommend waiting until 3 — the crib is a sleep boundary that works.' WHERE slug = 'safety-crib-to-bed-transition';
UPDATE milestone_windows SET jack_bridge = 'Answer the M-CHAT honestly — early identification before 24 months is when intervention works best.' WHERE slug = 'screening-visit-18months-autism';
UPDATE milestone_windows SET jack_bridge = 'The child who had their own emotions recognized learns to recognize emotions in others.' WHERE slug = 'social-empathy-emerging';
UPDATE milestone_windows SET jack_bridge = 'The ''me do it'' insistence is not defiance — it''s the emergence of a healthy drive for autonomy.' WHERE slug = 'social-independence-me-do-it';
UPDATE milestone_windows SET jack_bridge = 'This is not a discipline problem — it is a brain development problem. The prefrontal cortex barely exists.' WHERE slug = 'social-tantrums-peak';
UPDATE milestone_windows SET jack_bridge = 'Starting before readiness makes the process longer, not shorter.' WHERE slug = 'self-help-potty-readiness';
UPDATE milestone_windows SET jack_bridge = 'Every ''what''s that?'' is a vocabulary request. Every ''why?'' is a lesson in causal thinking.' WHERE slug = 'language-question-asking';
UPDATE milestone_windows SET jack_bridge = 'Copying a line requires analyzing a shape and planning the hand movement to replicate it.' WHERE slug = 'motor-drawing-line';
UPDATE milestone_windows SET jack_bridge = 'Jumping requires both feet to coordinate for takeoff — a bilateral gross motor milestone.' WHERE slug = 'motor-jumping-both-feet';
UPDATE milestone_windows SET jack_bridge = 'Size comparison is one of the earliest mathematical concepts — and it starts with big and little.' WHERE slug = 'cognitive-big-little';
UPDATE milestone_windows SET jack_bridge = 'Two steps requires holding two pieces of information in working memory while acting on them in sequence.' WHERE slug = 'language-2step-commands';
UPDATE milestone_windows SET jack_bridge = 'Using ''I'' correctly requires understanding that the word changes based on who is speaking.' WHERE slug = 'language-pronouns';
UPDATE milestone_windows SET jack_bridge = 'Below this threshold, a speech evaluation is worth having — early therapy produces the best outcomes.' WHERE slug = 'language-stranger-understands-50pct';
UPDATE milestone_windows SET jack_bridge = 'Below 50 words is the flag — 200 is the target, and the range between them is wide.' WHERE slug = 'language-vocab-200-words';
UPDATE milestone_windows SET jack_bridge = 'Moving from scribbling to copying means the brain can now analyze a shape and recreate it.' WHERE slug = 'cognitive-draw-copy-lines';
UPDATE milestone_windows SET jack_bridge = 'A real throw requires the arm and the opposite leg to coordinate — a genuine bilateral milestone.' WHERE slug = 'motor-throw-overarm';
UPDATE milestone_windows SET jack_bridge = 'Reciting 1 to 10 is sequence memory — understanding that each number means one object comes later.' WHERE slug = 'cognitive-counts-to-10';
UPDATE milestone_windows SET jack_bridge = 'Recalling what happened yesterday is the beginning of episodic memory.' WHERE slug = 'cognitive-memory-recalls-events';
UPDATE milestone_windows SET jack_bridge = 'These two letters are the same. These are different. Reading comprehension starts with this distinction.' WHERE slug = 'cognitive-same-different';
UPDATE milestone_windows SET jack_bridge = 'Understanding ''this afternoon'' is what lets a child hold the concept of a promise.' WHERE slug = 'cognitive-time-concepts';
UPDATE milestone_windows SET jack_bridge = 'Three words together is the bridge from labeling to grammar.' WHERE slug = 'language-3-word-sentences';
UPDATE milestone_windows SET jack_bridge = 'Up to 100 questions per hour — the quality of your answers predicts their scientific reasoning.' WHERE slug = 'language-asks-why';
UPDATE milestone_windows SET jack_bridge = 'Color names are abstract labels for properties, not things — linguistically more complex than naming objects.' WHERE slug = 'language-names-colors';
UPDATE milestone_windows SET jack_bridge = '75% stranger intelligibility is the clinical benchmark at 3 years — below this, a speech eval is indicated.' WHERE slug = 'language-stranger-understands-75pct';
UPDATE milestone_windows SET jack_bridge = 'Catching requires predicting where the ball will be — visual-motor planning in real time.' WHERE slug = 'motor-catching-ball';
UPDATE milestone_windows SET jack_bridge = 'A circle requires more wrist control and planning than a straight line — it''s letter readiness.' WHERE slug = 'motor-drawing-circle';
UPDATE milestone_windows SET jack_bridge = 'Jumping forward requires coordinating takeoff and landing simultaneously — harder than jumping in place.' WHERE slug = 'motor-jumping-forward';
UPDATE milestone_windows SET jack_bridge = 'Whole milk up to 2 for brain development, then 2% — it''s a single decision, not a gradual change.' WHERE slug = 'nutrition-2pct-milk-switch';
UPDATE milestone_windows SET jack_bridge = 'The transition is based on outgrowing the seat by weight or height — not by birthday.' WHERE slug = 'safety-forward-facing-transition';
UPDATE milestone_windows SET jack_bridge = 'The second autism screen catches children who passed at 18 months — both screens matter.' WHERE slug = 'screening-visit-24months-autism';
UPDATE milestone_windows SET jack_bridge = 'Playing with instead of alongside requires theory of mind and enough impulse control to take turns.' WHERE slug = 'social-cooperative-play';
UPDATE milestone_windows SET jack_bridge = 'Forcing sharing before age 3 teaches compliance under duress — it doesn''t teach generosity.' WHERE slug = 'social-sharing-not-before-3';
UPDATE milestone_windows SET jack_bridge = 'Saying the wrong word on purpose to make you laugh — that''s early theory of mind in action.' WHERE slug = 'cognitive-humor-jokes';
UPDATE milestone_windows SET jack_bridge = 'Hand preference is neurological, not a habit — attempting to change it causes real harm.' WHERE slug = 'motor-handedness-emerging';
UPDATE milestone_windows SET jack_bridge = 'A balance bike gives children something they''ve never had before: choosing where to go independently.' WHERE slug = 'motor-tricycle-balance-bike';
UPDATE milestone_windows SET jack_bridge = 'Undressing always comes before dressing — and getting pants down fast matters when potty training.' WHERE slug = 'self-help-undressing-independently';
UPDATE milestone_windows SET jack_bridge = 'Touching each object once while counting is fundamentally different from reciting numbers.' WHERE slug = 'language-counts-objects-5';
UPDATE milestone_windows SET jack_bridge = 'Counting to 3 is sequence memory — understanding that each number means one object comes next.' WHERE slug = 'language-counts-to-3';
UPDATE milestone_windows SET jack_bridge = 'Mechanics first, then reliability — daytime dryness is the finish line, not the starting gun.' WHERE slug = 'self-help-daytime-dryness';
UPDATE milestone_windows SET jack_bridge = 'The habit formed at 2 or 3 lasts a lifetime — let them hold the brush.' WHERE slug = 'self-help-tooth-brushing';
UPDATE milestone_windows SET jack_bridge = 'Following four steps without prompting is a school readiness skill — it takes all three cognitive systems.' WHERE slug = 'language-complex-instructions';
UPDATE milestone_windows SET jack_bridge = 'Four words together means language is doing real communicative work, not just labeling.' WHERE slug = 'language-full-sentences';
UPDATE milestone_windows SET jack_bridge = 'A child who can say their name and age is meaningfully safer in a crowd.' WHERE slug = 'language-knows-name-age';
UPDATE milestone_windows SET jack_bridge = 'Hopping on one foot is the precursor to skipping — dynamic single-leg balance in action.' WHERE slug = 'motor-hopping-one-foot';
UPDATE milestone_windows SET jack_bridge = 'Added to the AAP schedule specifically because the gap between 24 and 36 months is when language delays entrench.' WHERE slug = 'screening-visit-30months';
UPDATE milestone_windows SET jack_bridge = 'Wanting a specific friend by name — that''s the beginning of selective social bonding.' WHERE slug = 'social-peer-friendships';
UPDATE milestone_windows SET jack_bridge = 'By 3, they have the cognitive capacity for real sharing — not just compliance under duress.' WHERE slug = 'social-sharing-scaffolding';
UPDATE milestone_windows SET jack_bridge = 'Two seconds on one foot sounds simple — it requires precise vestibular and proprioceptive control.' WHERE slug = 'motor-balance-one-foot';
UPDATE milestone_windows SET jack_bridge = 'Requesting a specific friend by name is the first sign of selective social bonding beyond the family.' WHERE slug = 'social-named-friendships';
UPDATE milestone_windows SET jack_bridge = 'Most children count to 10 before they understand that ''two'' means exactly two objects.' WHERE slug = 'cognitive-number-quantity';
UPDATE milestone_windows SET jack_bridge = 'Preschool readiness is not about counting or colors — it''s about functioning in a group without a parent.' WHERE slug = 'cognitive-preschool-readiness';
UPDATE milestone_windows SET jack_bridge = 'Getting dressed independently is a preschool readiness requirement — and the groundwork starts at 2.5.' WHERE slug = 'self-help-dressing-simple-clothes';
UPDATE milestone_windows SET jack_bridge = 'Describing what happened at the park is the first narrative structure — a direct predictor of reading comprehension.' WHERE slug = 'language-tells-stories';
UPDATE milestone_windows SET jack_bridge = 'This is the last annual visit before age 4 — the end of the most intensively monitored developmental period.' WHERE slug = 'screening-visit-36months';
